# Structure de base
version: "3.8"

services:
  # Déclaration du container de base de donnée
  base:
    container_name: maBdd
    image: mariadb:latest
    user: ""
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

    ports:
      - "3307:3306"

    volumes:
      - ./mysql:/var/lib/mysql

  # Déclaration du container PHP
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/symfo
    depends_on:
      - base

  # Création du serveur web
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/symfo
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - base

volumes:
  mysql:
