controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# ma première route
#app_home:
#    path: /home
#    controller: App\Controller\HomeController::bienvenue